{{- if .Values.storage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supachart.storage.fullname" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.storage.service.type }}
  ports:
    - name: http
      port: {{ .Values.storage.service.port }}
      targetPort: 5000
      protocol: TCP
  selector: {{ include "supachart.storage.selectorLabels" . | nindent 4 }}
{{- end }}
