{{- if .Values.realtime.enabled }}
{{- if .Values.realtime.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supachart.realtime.serviceAccountName" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.realtime.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
