{{- if .Values.functions.enabled }}
{{- if .Values.functions.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supachart.functions.serviceAccountName" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.functions.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
