{{- if .Values.auth.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supachart.auth.fullname" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "supachart.auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "supachart.auth.selectorLabels" . | nindent 8 }}
      annotations: {{- toYaml .Values.auth.deployment.annotations | nindent 8 }}
    spec:
      {{- if .Values.auth.serviceAccount.enabled }}
      serviceAccountName: {{ include "supachart.auth.serviceAccountName" . }}
      {{- end }}
      securityContext: {{- toYaml .Values.auth.deployment.securityContext | nindent 8 }}
      initContainers:
        {{ include "supachart.waitForDbInitContainer" . | nindent 8 }}
      containers:
        - name: {{ include "supachart.auth.name" . }}
          image: {{ .Values.auth.deployment.image }}
          imagePullPolicy: {{ .Values.auth.deployment.imagePullPolicy }}
          livenessProbe:
            httpGet:
              path: /health
              port: 9999
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 5 
            failureThreshold: 3 
          startupProbe:
            httpGet:
              path: /health
              port: 9999
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          ports:
            - containerPort: 9999
              name: http
          env:
            {{- include "supachart.env" (dict "name" "POSTGRES_PASSWORD"                       "path" .Values.db.password ) | nindent 12 }}
            - name: POSTGRES_PORT
              value: {{ .Values.db.service.port | quote }}
            {{- include "supachart.env" (dict "name" "POSTGRES_DB"                             "path" .Values.db.database ) | nindent 12 }}
            - name: POSTGRES_HOST
              value: {{ include "supachart.db.fullname" . | quote }}
            - name: GOTRUE_API_HOST
              value: "0.0.0.0"
            - name: GOTRUE_API_PORT
              value: "9999"
            {{- include "supachart.env" (dict "name" "API_EXTERNAL_URL"                        "path" .Values.shared.public_url ) | nindent 12 }}
            - name: GOTRUE_DB_DRIVER
              value: "postgres"
            - name: GOTRUE_DB_DATABASE_URL
              value: "postgres://supabase_auth_admin:$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
            {{- include "supachart.env" (dict "name" "GOTRUE_SITE_URL"                         "path" .Values.shared.site_url ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_URI_ALLOW_LIST"                   "path" .Values.shared.additional_redirect_urls ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_DISABLE_SIGNUP"                   "path" .Values.auth.settings.disable_signup ) | nindent 12 }}
            - name: GOTRUE_JWT_ADMIN_ROLES
              value: "service_role"
            - name: GOTRUE_JWT_AUD
              value: "authenticated"
            - name: GOTRUE_JWT_DEFAULT_GROUP_NAME
              value: "authenticated"
            {{- include "supachart.env" (dict "name" "GOTRUE_JWT_EXP"                          "path" .Values.auth.jwt.expiry ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_JWT_SECRET"                       "path" .Values.auth.jwt.secret ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_EXTERNAL_EMAIL_ENABLED"           "path" .Values.auth.settings.email.enable_signup ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED" "path" .Values.auth.settings.enable_anonymous_users ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_MAILER_AUTOCONFIRM"               "path" .Values.auth.settings.email.enable_autoconfirm ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_EXTERNAL_PHONE_ENABLED"           "path" .Values.auth.settings.phone.enable_signup ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_SMS_AUTOCONFIRM"                  "path" .Values.auth.settings.phone.enable_autoconfirm ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_SMTP_ADMIN_EMAIL"                 "path" .Values.auth.settings.email.admin_email ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_SMTP_HOST"                        "path" .Values.auth.settings.email.host ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_SMTP_PORT"                        "path" .Values.auth.settings.email.port ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_SMTP_USER"                        "path" .Values.auth.settings.email.user ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_SMTP_PASS"                        "path" .Values.auth.settings.email.password ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_SMTP_SENDER_NAME"                 "path" .Values.auth.settings.email.sender_name ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_MAILER_URLPATHS_INVITE"           "path" .Values.auth.settings.mailer.urlpaths.invite ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_MAILER_URLPATHS_CONFIRMATION"     "path" .Values.auth.settings.mailer.urlpaths.confirmation ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_MAILER_URLPATHS_RECOVERY"         "path" .Values.auth.settings.mailer.urlpaths.recovery ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE"     "path" .Values.auth.settings.mailer.urlpaths.email_change ) | nindent 12 }}
{{- end }}
