{{- if .Values.auth.enabled }}
{{- if .Values.auth.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
authdata:
  name: {{ include "supachart.auth.serviceAccountName" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.auth.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
