# Default values for supachart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

db:
  enabled: true
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    enabled: true
    name: ""
    annotations: {}
  service:
    type: ClusterIP
    port: 5432