{{- if .Values.studio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supachart.studio.fullname" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "supachart.studio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "supachart.studio.selectorLabels" . | nindent 8 }}
      annotations: {{- toYaml .Values.studio.deployment.annotations | nindent 8 }}
    spec:
       {{- if .Values.studio.serviceAccount.enabled }}
      serviceAccountName: {{ include "supachart.studio.serviceAccountName" . }}
      {{- end }}
      securityContext: {{- toYaml .Values.studio.deployment.securityContext | nindent 8 }}
      containers:
        - name: {{ include "supachart.studio.name" . }}
          image: {{ .Values.studio.deployment.image }}
          imagePullPolicy: {{ .Values.studio.deployment.imagePullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: STUDIO_PG_META_URL
              value: "http://{{ include "supachart.meta.fullname" . }}:{{ .Values.meta.service.port }}"
            {{- include "supachart.env" (dict "name" "POSTGRES_PASSWORD"         "path" .Values.db.password                ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "DEFAULT_ORGANIZATION_NAME" "path" .Values.studio.defaultOrganization ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "DEFAULT_PROJECT_NAME"      "path" .Values.studio.defaultProject      ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "OPENAI_API_KEY"            "path" .Values.studio.openai.apiKey       ) | nindent 12 }}
            - name: SUPABASE_URL
              value: "http://{{ include "supachart.kong.fullname" . }}:{{ .Values.kong.service.port }}"
            {{- include "supachart.env" (dict "name" "SUPABASE_PUBLIC_URL"       "path" .Values.shared.public_url          ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "SUPABASE_ANON_KEY"         "path" .Values.shared.anon_key            ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "SUPABASE_SERVICE_KEY"      "path" .Values.shared.service_role_key    ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "AUTH_JWT_SECRET"           "path" .Values.auth.jwt.secret            ) | nindent 12 }}
{{- end }}
