{{- if .Values.studio.enabled }}
{{- if .Values.studio.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supachart.studio.serviceAccountName" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.studio.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
