{{- if .Values.meta.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supachart.meta.fullname" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "supachart.meta.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "supachart.meta.selectorLabels" . | nindent 8 }}
      annotations: {{- toYaml .Values.meta.deployment.annotations | nindent 8 }}
    spec:
      {{- if .Values.meta.serviceAccount.enabled }}
      serviceAccountName: {{ include "supachart.meta.serviceAccountName" . }}
      {{- end }}
      securityContext: {{- toYaml .Values.meta.deployment.securityContext | nindent 8 }}
      containers:
        - name: {{ include "supachart.meta.name" . }}
          image: {{ .Values.meta.deployment.image }}
          imagePullPolicy: {{ .Values.meta.deployment.imagePullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PG_META_PORT
              value: "8080"
            - name: PG_META_DB_HOST
              value: {{ include "supachart.db.fullname" . | quote }}
            - name: PG_META_DB_PORT
              value: {{ .Values.db.service.port | quote }}
            {{- include "supachart.env" (dict "name" "POSTGRES_DB"         "path" .Values.db.database ) | nindent 12 }}
            - name: PG_META_DB_USER
              value: "supabase_admin"
            {{- include "supachart.env" (dict "name" "PG_META_DB_PASSWORD" "path" .Values.db.password ) | nindent 12 }}
{{- end }}
