{{- if .Values.meta.enabled }}
{{- if .Values.meta.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supachart.meta.serviceAccountName" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.meta.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
