{{- if .Values.kong.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supachart.kong.fullname" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "supachart.kong.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "supachart.kong.selectorLabels" . | nindent 8 }}
      annotations: {{- toYaml .Values.kong.deployment.annotations | nindent 8 }}
    spec:
      {{- if .Values.kong.serviceAccount.enabled }}
      serviceAccountName: {{ include "supachart.kong.serviceAccountName" . }}
      {{- end }}
      securityContext: {{- toYaml .Values.kong.deployment.securityContext | nindent 8 }}
      containers:
        - name: {{ include "supachart.kong.name" . }}
          image: {{ .Values.kong.deployment.image }}
          imagePullPolicy: {{ .Values.kong.deployment.imagePullPolicy }}
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: kong-config
              mountPath: /etc/kong/kong.yml
              subPath: kong.yml
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/etc/kong/kong.yml"
            - name: KONG_DNS_ORDER
              value: "LAST,A,CNAME"
            - name: KONG_PLUGINS
              value: "request-transformer,cors,key-auth,acl,basic-auth"
            - name: KONG_NGINX_PROXY_PROXY_BUFFER_SIZE
              value: "160k"
            - name: KONG_NGINX_PROXY_PROXY_BUFFERS
              value: "64 160k"
      initContainers:
        - name: generate-kong-config
          image: bash:5
          command: ["/usr/local/bin/bash", "-c"]
          args:
            - |
              apk add --no-cache gettext && \
              envsubst < /template/kong.yml > /config/kong.yml
          volumeMounts:
            - name: kong-template
              mountPath: /template
            - name: kong-config
              mountPath: /config
          env:
            {{- include "supachart.env" (dict "name" "DASHBOARD_USERNAME"   "path" .Values.studio.dashboard.username ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "DASHBOARD_PASSWORD"   "path" .Values.studio.dashboard.password ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "SUPABASE_ANON_KEY"    "path" .Values.shared.anon_key           ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "SUPABASE_SERVICE_KEY" "path" .Values.shared.service_role_key   ) | nindent 12 }}
            - name: SUPACHART_META_URL
              value: "http://{{ include "supachart.meta.fullname" . }}:{{ .Values.meta.service.port }}"
            - name: SUPACHART_STUDIO_URL
              value: "http://{{ include "supachart.studio.fullname" . }}:{{ .Values.studio.service.port }}"
            - name: SUPACHART_AUTH_URL
              value: "http://{{ include "supachart.auth.fullname" . }}:{{ .Values.auth.service.port }}"
            - name: SUPACHART_FUNCTIONS_URL
              value: "http://{{ include "supachart.functions.fullname" . }}:{{ .Values.functions.service.port }}"
            - name: SUPACHART_ANALYTICS_URL
              value: "http://{{ include "supachart.analytics.fullname" . }}:{{ .Values.analytics.service.port }}"
            - name: SUPACHART_REST_URL
              value: "http://{{ include "supachart.rest.fullname" . }}:{{ .Values.rest.service.port }}"
            - name: SUPACHART_STORAGE_URL
              value: "http://{{ include "supachart.storage.fullname" . }}:{{ .Values.storage.service.port }}"
            - name: SUPACHART_REALTIME_URL
              value: "http://{{ include "supachart.realtime.fullname" . }}:{{ .Values.realtime.service.port }}"
      volumes:
        - name: kong-config
          emptyDir: {}
        - name: kong-template
          configMap:
            name: {{ include "supachart.kong.fullname" . }}-config
{{- end }}
