{{- if .Values.kong.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supachart.kong.fullname" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kong.service.type }}
  ports:
    - name: http
      port: {{ .Values.kong.service.port }}
      targetPort: 8000
      protocol: TCP
  selector: {{ include "supachart.kong.selectorLabels" . | nindent 4 }}
{{- end }}
