{{- if .Values.kong.enabled }}
{{- if .Values.kong.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supachart.kong.serviceAccountName" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.kong.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
