apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supachart.db.fullname" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
spec:
  replicas: 1 # There is no scaling support for the database, it should always run as a single instance
  selector:
    matchLabels: {{ include "supachart.db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "supachart.db.selectorLabels" . | nindent 8 }}
      annotations: {{- toYaml .Values.db.deployment.annotations | nindent 8 }}
    spec:
      {{- if .Values.db.serviceAccount.enabled }}
      serviceAccountName: {{ include "supachart.db.serviceAccountName" . }}
      {{- end }}
      securityContext: {{- toYaml .Values.db.deployment.securityContext | nindent 8 }}
      {{- if .Values.db.persistence.enabled }}
      initContainers:
        - name: copy-defaults
          image: {{ .Values.db.deployment.image }}
          imagePullPolicy: {{ .Values.db.deployment.imagePullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
              - |
                if [ ! -f /mnt/postgresql-custom/supautils.conf ]; then
                  cp -a /etc/postgresql-custom/. /mnt/postgresql-custom/
                fi
                chown -R 105:106 /mnt/postgresql-data
                chmod 750 /mnt/postgresql-data
          volumeMounts:
            - mountPath: /mnt/postgresql-custom
              name: db-config
            - mountPath: /mnt/postgresql-data
              name: db-data
              subPath: postgresql-data/
      {{- end }}
      containers:
        - name: {{ include "supachart.db.name" . }}
          image: {{ .Values.db.deployment.image }}
          imagePullPolicy: {{ .Values.db.deployment.imagePullPolicy }}
          ports:
            - containerPort: 5432
              name: postgres
          securityContext:
            runAsUser: 105
            runAsGroup: 106
          command: {{- toYaml .Values.db.deployment.command | nindent 12 }}
          args: {{- toYaml .Values.db.deployment.args | nindent 12 }}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init-scripts/
              name: init-scripts
            - mountPath: /docker-entrypoint-initdb.d/migrations/
              name: migrations
            {{- if .Values.db.persistence.enabled }}
            - mountPath: /etc/postgresql-custom
              name: db-config
            - mountPath: /var/lib/postgresql/data
              name: db-data
              # For compatibility with ext4 lost+found
              subPath: postgresql-data/
            {{- end }}
          env:
            - name: POSTGRES_HOST
              value: /var/run/postgresql
            - name: PGPORT
              value: "5432"
            - name: POSTGRES_PORT
              value: "5432"
            {{- include "supachart.env" (dict "name" "PGPASSWORD"        "path" .Values.db.password     ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "POSTGRES_PASSWORD" "path" .Values.db.password     ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "PGUSER"            "path" .Values.db.username     ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "POSTGRES_USER"     "path" .Values.db.username     ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "PGDATABASE"        "path" .Values.db.database     ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "POSTGRES_DB"       "path" .Values.db.database     ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "JWT_SECRET"        "path" .Values.auth.jwt.secret ) | nindent 12 }}
            {{- include "supachart.env" (dict "name" "JWT_EXP"           "path" .Values.auth.jwt.expiry ) | nindent 12 }}
      volumes:
        - name: init-scripts
          configMap:
            name: {{ include "supachart.db.fullname" . }}-init-scripts
        - name: migrations
          configMap:
            name: {{ include "supachart.db.fullname" . }}-migrations
        {{- if .Values.db.persistence.enabled }}
        - name: db-data
          persistentVolumeClaim:
           claimName: {{ include "supachart.db.fullname" . }}-data
        - name: db-config
          persistentVolumeClaim:
            claimName: {{ include "supachart.db.fullname" . }}-config
        {{- end }}
