apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "supachart.db.fullname" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
  storageClassName: {{ .Values.db.persistence.storageClass }}
