{{- if .Values.db.enabled -}}
{{- if .Values.db.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "supachart.db.fullname" . }}-data
  labels: {{- include "supachart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
  storageClassName: {{ .Values.db.persistence.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "supachart.db.fullname" . }}-config
  labels: {{- include "supachart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Mi
  storageClassName: {{ .Values.db.persistence.storageClass }}
{{- end -}}
{{- end -}}