{{- if .Values.db.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supachart.fullname" . }}-db
  labels:
    {{- include "supachart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.serviceType }}
  ports:
    - name: db
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.targetPort }}
  selector:
    app: {{ include "supachart.db.selectorLabels" . | nindent 4 }}
{{- end }}
