{{- if .Values.db.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supachart.fullname" . }}-db
  labels:
    {{- include "supachart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.db.service.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    {{ include "supachart.db.selectorLabels" . | nindent 4 }}
{{- end }}
