{{- if .Values.db.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supachart.db.serviceAccountName" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.db.serviceAccount.annotations | nindent 4 }}
{{- end }}
