{{- if .Values.vector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supachart.vector.fullname" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "supachart.vector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "supachart.vector.selectorLabels" . | nindent 8 }}
      annotations: {{- toYaml .Values.vector.deployment.annotations | nindent 8 }}
    spec:
      {{- if .Values.vector.serviceAccount.enabled }}
      serviceAccountName: {{ include "supachart.vector.serviceAccountName" . }}
      {{- end }}
      securityContext: {{- toYaml .Values.vector.deployment.securityContext | nindent 8 }}
      initContainers:
        {{ include "supachart.waitForDbInitContainer" . | nindent 8 }}
      containers:
        - name: {{ include "supachart.vector.name" . }}
          image: {{ .Values.vector.deployment.image }}
          imagePullPolicy: {{ .Values.vector.deployment.imagePullPolicy }}
          livenessProbe:
            httpGet:
              path: /health
              port: 9001
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 9001
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          ports:
            - containerPort: 9001
              name: http
          args:
            - "--config"
            - "/etc/vector/vector.yml"
          env:
            {{- if .Values.analytics.enabled }}
            {{- include "supachart.env" (dict "name" "LOGFLARE_PUBLIC_ACCESS_TOKEN"   "path" .Values.analytics.access_token.public ) | nindent 12 }}
            {{- end }}
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: vector-logs
              mountPath: /etc/vector/vector.yml
              subPath: vector.yml
      volumes:
        - name: vector-logs
          configMap:
            name: {{ include "supachart.vector.fullname" . }}-config
{{- end }}
