{{- if .Values.vector.enabled }}
{{- if .Values.vector.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supachart.vector.serviceAccountName" . }}
  labels: {{- include "supachart.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.vector.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
